import asyncio, json, logging, math, os, random, re, shutil, sqlite3, subprocess, sys, time, traceback
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from aiohttp import web
from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Update
from telegram.ext import (
    Application, CallbackQueryHandler, CommandHandler,
    ContextTypes, MessageHandler, filters,
)
import yt_dlp

# ═══════════════════════════════════════════════════════════
# الإعدادات الأساسية
# ═══════════════════════════════════════════════════════════
BOT_NAME = "⚡ YAMD – Ultra Speed"
BOT_FULL_NAME = "YAAQOB ALMAHAJERI MEDIA DOWNLOADER"

BOT_TOKEN = os.environ.get("BOT_TOKEN", "").strip()
ADMIN_ID = int(os.environ.get("ADMIN_ID", "0") or "0")
WEBHOOK_URL = os.environ.get("WEBHOOK_URL", "").rstrip("/")
PORT = int(os.environ.get("PORT", "8080") or "8080")

# ✅ دعم البروكسيات الدوارة
PROXY_LIST_RAW = os.environ.get("PROXY_LIST", "").strip()
PROXY_POOL: List[str] = []
if PROXY_LIST_RAW:
    for line in PROXY_LIST_RAW.splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            parts = line.split(":")
            if len(parts) == 4:
                ip, port, user, pwd = parts
                proxy_url = f"http://{user}:{pwd}@{ip}:{port}"
                PROXY_POOL.append(proxy_url)
            elif len(parts) == 2:
                ip, port = parts
                proxy_url = f"http://{ip}:{port}"
                PROXY_POOL.append(proxy_url)
    if PROXY_POOL:
        print(f"🌐 Loaded {len(PROXY_POOL)} proxies")
    else:
        print("⚠️ PROXY_LIST defined but no valid proxies parsed")
else:
    SINGLE_PROXY = os.environ.get("PROXY_URL", "").strip()
    if SINGLE_PROXY:
        PROXY_POOL.append(SINGLE_PROXY)

PO_TOKEN = os.environ.get("PO_TOKEN", "").strip()

MAX_SIZE = 48 * 1024 * 1024
DL_DIR = Path.home() / "yamd_dl"
DL_DIR.mkdir(parents=True, exist_ok=True)

DOWNLOAD_SEM = asyncio.Semaphore(2)

YT_CLIENTS = ["android_vr", "tv", "ios", "web", "mweb"]

PINTEREST_UA = "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Mobile Safari/537.36"
YT_UA = "com.google.android.youtube/20.10.38 (Linux; Android 14)"
COMMON_HEADERS = {"Accept-Language": "en-US,en;q=0.9"}

# ═══════════════════════════════════════════════════════════
# الكوكيز
# ═══════════════════════════════════════════════════════════
COOKIE_FILE: Optional[str] = None
COOKIE_TMP = "/tmp/yamd_cookies.txt"
COOKIES_TEXT = os.environ.get("COOKIES_TEXT", "")
SECRET_FILE = "/etc/secrets/cookies.txt"

def _load_cookies() -> None:
    global COOKIE_FILE
    if COOKIES_TEXT.strip():
        with open(COOKIE_TMP, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n# generated by YAMD\n")
            f.write(COOKIES_TEXT.strip())
        COOKIE_FILE = COOKIE_TMP
        print("🍪 Cookies loaded from COOKIES_TEXT")
        return
    if os.path.exists(SECRET_FILE):
        try:
            shutil.copy2(SECRET_FILE, COOKIE_TMP)
            COOKIE_FILE = COOKIE_TMP
            print("🍪 Cookies copied from Render Secret File")
            return
        except Exception as e:
            print(f"⚠️ Failed to copy secret file: {e}")
    print("⚠️ NO COOKIES FOUND – YouTube may require sign-in")

_load_cookies()

# ═══════════════════════════════════════════════════════════
# السجلات
# ═══════════════════════════════════════════════════════════
logging.basicConfig(
    level=logging.WARNING,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
    handlers=[logging.StreamHandler(sys.stdout), logging.FileHandler("yamd.log")],
)
logger = logging.getLogger("YAMD")
logger.setLevel(logging.INFO)
for lib in ("httpx", "httpcore", "telegram", "hpack", "asyncio", "aiohttp"):
    logging.getLogger(lib).setLevel(logging.ERROR)

# ═══════════════════════════════════════════════════════════
# قاعدة البيانات (مع عمود IP)
# ═══════════════════════════════════════════════════════════
db = sqlite3.connect("yamd.db", check_same_thread=False)
db.execute("PRAGMA journal_mode=WAL")
db.execute("PRAGMA synchronous=NORMAL")

def _setup_db() -> None:
    db.execute("CREATE TABLE IF NOT EXISTS users(uid INTEGER PRIMARY KEY, username TEXT, fname TEXT, lname TEXT, seen TEXT, active TEXT, cnt INTEGER DEFAULT 0, lang TEXT, premium INTEGER DEFAULT 0, ip TEXT)")
    db.execute("CREATE TABLE IF NOT EXISTS downloads(id INTEGER PRIMARY KEY AUTOINCREMENT, uid INTEGER, url TEXT, title TEXT, quality TEXT, size INTEGER, speed REAL, ts TEXT)")

    cols = {row[1] for row in db.execute("PRAGMA table_info(users)").fetchall()}
    if "lname" not in cols:
        db.execute("ALTER TABLE users ADD COLUMN lname TEXT")
    if "lang" not in cols:
        db.execute("ALTER TABLE users ADD COLUMN lang TEXT")
    if "premium" not in cols:
        db.execute("ALTER TABLE users ADD COLUMN premium INTEGER DEFAULT 0")
    if "ip" not in cols:
        db.execute("ALTER TABLE users ADD COLUMN ip TEXT")
    db.commit()
_setup_db()

def db_user(u) -> None:
    now = datetime.now().isoformat()
    db.execute(
        "INSERT INTO users(uid,username,fname,lname,seen,active,lang,premium) VALUES(?,?,?,?,?,?,?,?) "
        "ON CONFLICT(uid) DO UPDATE SET "
        "active=excluded.active, username=COALESCE(excluded.username,username), "
        "fname=COALESCE(excluded.fname,fname), lname=COALESCE(excluded.lname,lname), "
        "lang=COALESCE(excluded.lang,lang), premium=COALESCE(excluded.premium,premium)",
        (u.id, u.username or "", u.first_name or "", u.last_name or "",
         now, now, u.language_code or "", 1 if u.is_premium else 0)
    )
    db.commit()

def db_log(uid, url, title, qkey, size, speed):
    db.execute("INSERT INTO downloads(uid,url,title,quality,size,speed,ts) VALUES(?,?,?,?,?,?,?)", (uid, url, title, qkey, size, round(speed,1), datetime.now().isoformat()))
    db.execute("UPDATE users SET cnt=cnt+1 WHERE uid=?", (uid,))
    db.commit()

# ═══════════════════════════════════════════════════════════
# أدوات مساعدة
# ═══════════════════════════════════════════════════════════
_edit_ts = defaultdict(float)
def fmt_size(b): return f"{b/1024**3:.1f}GB" if b >= 1024**3 else f"{b/1024**2:.1f}MB" if b else "?"
def fmt_speed(kbs): return f"{kbs/1024:.1f}MB/s" if kbs and kbs >= 1024 else f"{kbs:.0f}KB/s" if kbs else "?"
async def safe_edit(msg, text, markup=None):
    if time.time() - _edit_ts[msg.message_id] < 2: return
    try: await msg.edit_text(text, reply_markup=markup); _edit_ts[msg.message_id] = time.time()
    except: pass

def is_youtube(url): return "youtube.com" in url.lower() or "youtu.be" in url.lower()
def is_pinterest(url): return "pin.it" in url.lower() or "pinterest" in url.lower()

def cleanup(prefix):
    for f in DL_DIR.glob(f"{prefix}*"):
        try: f.unlink() if f.is_file() else None
        except: pass

def find_file(prefix):
    cands = sorted([f for f in DL_DIR.glob(f"{prefix}*") if f.is_file()], key=lambda f: f.stat().st_size, reverse=True)
    return str(cands[0]) if cands else None

def split_video(filepath, max_part_size=MAX_SIZE):
    if not shutil.which("ffmpeg"): return None
    base = os.path.splitext(filepath)[0]; pattern = f"{base}_part%03d.mp4"
    try:
        dur = float(subprocess.run(["ffprobe","-v","quiet","-show_entries","format=duration","-of","csv=p=0",filepath], capture_output=True,text=True,timeout=60).stdout.strip())
    except: return None
    if dur <= 0: return None
    total = os.path.getsize(filepath)
    if total <= max_part_size: return [filepath]
    parts = math.ceil(total / max_part_size)
    seg = math.ceil(dur / parts) + 1
    try:
        subprocess.run(["ffmpeg","-y","-i",filepath,"-c","copy","-map","0","-f","segment","-segment_time",str(seg),"-reset_timestamps","1","-segment_format","mp4",pattern], check=True, capture_output=True, text=True, timeout=600)
    except: return None
    return [str(p) for p in sorted(Path(base).parent.glob(f"{Path(filepath).stem}_part*.mp4"))]

async def cleanup_task():
    while True:
        now = time.time()
        for f in DL_DIR.glob("*"):
            try:
                if f.is_file() and now - f.stat().st_mtime > 3600: f.unlink()
            except: pass
        await asyncio.sleep(1800)

# ═══════════════════════════════════════════════════════════
# اختيار بروكسي عشوائي
# ═══════════════════════════════════════════════════════════
def get_random_proxy() -> Optional[str]:
    if PROXY_POOL:
        return random.choice(PROXY_POOL)
    return None

# ═══════════════════════════════════════════════════════════
# تحديث yt-dlp
# ═══════════════════════════════════════════════════════════
async def _ensure_ytdlp_updated():
    try:
        proc = await asyncio.create_subprocess_exec(
            sys.executable, "-m", "pip", "install", "-U", "--pre", "yt-dlp",
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE
        )
        stdout, stderr = await proc.communicate()
        if proc.returncode == 0:
            logger.info("✅ yt-dlp updated to nightly/pre-release")
        else:
            proc2 = await asyncio.create_subprocess_exec(
                sys.executable, "-m", "pip", "install", "-U", "yt-dlp",
                stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE
            )
            await proc2.communicate()
            logger.info("✅ yt-dlp updated to stable")
    except Exception as e:
        logger.warning(f"⚠️ Could not update yt-dlp: {e}")

# ═══════════════════════════════════════════════════════════
# استخراج التنسيقات
# ═══════════════════════════════════════════════════════════
def _build_extractor_args(client: str) -> dict:
    args = {
        "youtube": {
            "player_client": client,
            "formats": "missing_pot",
        }
    }
    if PO_TOKEN and client in ("web", "mweb", "ios", "android"):
        args["youtube"]["po_token"] = f"{client}.player+{PO_TOKEN}"
    if client in ("android_vr", "tv"):
        args["youtube"]["player_skip"] = "webpage,configs,js"
    return args

def _api_extract(url: str, extractor_args: dict, extra_opts: dict = None) -> dict:
    opts = {
        "quiet": True,
        "no_warnings": True,
        "noprogress": True,
        "extract_flat": False,
        "ignore_no_formats_error": True,
        "no_check_formats": True,
        "skip_download": True,
        "geo_bypass": True,
        "cookiefile": COOKIE_FILE if COOKIE_FILE and os.path.exists(COOKIE_FILE) else None,
        "http_headers": {"User-Agent": YT_UA, **COMMON_HEADERS},
        "extractor_args": extractor_args,
    }
    proxy = get_random_proxy()
    if proxy:
        opts["proxy"] = proxy
    if extra_opts:
        opts.update(extra_opts)
    try:
        with yt_dlp.YoutubeDL(opts) as ydl:
            return ydl.extract_info(url, download=False)
    except Exception as e:
        raise RuntimeError(str(e)[:400])

def extract_formats(url: str) -> Tuple[dict, list, Optional[dict]]:
    if not is_youtube(url):
        opts = {
            "quiet": True, "no_warnings": True, "extract_flat": False,
            "ignore_no_formats_error": True, "no_check_formats": True,
            "cookiefile": COOKIE_FILE if COOKIE_FILE and os.path.exists(COOKIE_FILE) else None,
        }
        proxy = get_random_proxy()
        if proxy:
            opts["proxy"] = proxy
        if is_pinterest(url):
            opts["http_headers"] = {"User-Agent": PINTEREST_UA}
        with yt_dlp.YoutubeDL(opts) as ydl:
            info = ydl.extract_info(url, download=False)
        return parse_formats(info)

    strategies = [_build_extractor_args(client) for client in YT_CLIENTS]
    last_err = ""
    for i, strat in enumerate(strategies, 1):
        client_name = strat["youtube"]["player_client"]
        try:
            logger.info(f"🔄 Trying YouTube client: {client_name}")
            info = _api_extract(url, strat)
            if not info.get("formats") and i < len(strategies):
                last_err = f"Strategy {i} ({client_name}): no formats extracted"
                continue
            logger.info(f"✅ Success with client: {client_name}")
            return parse_formats(info)
        except Exception as e:
            last_err = f"Strategy {i} ({client_name}): {str(e)}"
            logger.warning(last_err)
            continue

    try:
        logger.info("🔄 Fallback: trying generic 'best' format")
        info = _api_extract(url, {"youtube": {"player_client": "web"}}, {"format": "best"})
        return parse_formats(info)
    except Exception as e:
        raise RuntimeError(f"جميع الاستراتيجيات فشلت. آخر خطأ: {last_err}")

def parse_formats(info: dict) -> Tuple[dict, list, Optional[dict]]:
    formats = info.get("formats") or info.get("entries", [{}])[0].get("formats") or []
    if not formats:
        logger.warning("No formats found, creating minimal fallback")
        direct_url = info.get("url") or ""
        if direct_url:
            return info, [{"height": info.get("height") or 720, "filesize": info.get("filesize") or 0, "ext": info.get("ext", "mp4"), "format_id": "fallback", "acodec": "aac", "vcodec": "avc1", "url": direct_url}], None
        else:
            raise RuntimeError("YouTube لم يُرجع أي تنسيقات صالحة.")
    
    video_fmts = []
    audio_fmts = []
    seen = set()
    for f in formats:
        try:
            fid = str(f.get("format_id") or "")
            vc = f.get("vcodec"); ac = f.get("acodec")
            h = f.get("height") or 0; w = f.get("width") or 0
            ext = f.get("ext") or "mp4"
            sz = f.get("filesize") or f.get("filesize_approx") or 0
            is_vid = h > 0 or (vc and vc != "none")
            if is_vid:
                if not h and w:
                    if w >= 3840: h = 2160
                    elif w >= 2560: h = 1440
                    elif w >= 1920: h = 1080
                    elif w >= 1280: h = 720
                    elif w >= 854: h = 480
                    elif w >= 640: h = 360
                    else: h = 240
                if h <= 0: continue
                key = (h, ext)
                if key in seen: continue
                seen.add(key)
                video_fmts.append({"height": h, "filesize": sz, "ext": ext, "format_id": fid, "acodec": ac, "vcodec": vc})
            if ac and ac != "none" and (vc == "none" or not vc):
                audio_fmts.append({"abr": f.get("abr", 0), "filesize": sz, "ext": ext, "format_id": fid})
        except: pass
    if not video_fmts:
        for f in formats:
            try:
                note = str(f.get("format_note") or "")
                m = re.search(r"(\d{3,4})p", note)
                if m:
                    h = int(m.group(1))
                    video_fmts.append({"height": h, "filesize": f.get("filesize", 0), "ext": f.get("ext", "mp4"), "format_id": str(f.get("format_id", "")), "acodec": f.get("acodec"), "vcodec": f.get("vcodec")})
            except: pass
    video_fmts.sort(key=lambda x: x["height"], reverse=True)
    best_audio = max(audio_fmts, key=lambda x: x["abr"] or 0) if audio_fmts else None
    return info, video_fmts, best_audio

# ═══════════════════════════════════════════════════════════
# التحميل العام
# ═══════════════════════════════════════════════════════════
def _locate_file(raw, vid_id, qtype):
    exts = ["mp3"] if qtype=="a" else ["mp4","mkv","webm",""]
    for e in exts:
        p = os.path.splitext(raw)[0] + (f".{e}" if e else "")
        if os.path.exists(p): return p
    cands = sorted([f for f in DL_DIR.glob(f"{vid_id}*") if f.is_file()], key=lambda f: f.stat().st_size, reverse=True)
    return str(cands[0]) if cands else None

async def do_download(ctx, chat_id, url, fmt_str, qtype, status_msg, uid):
    async with DOWNLOAD_SEM:
        loop = asyncio.get_running_loop()
        t0 = time.time()
        vid_id = f"v{uid}{int(t0)}"
        if not fmt_str or fmt_str == "None":
            fmt_str = "bestvideo+bestaudio/best" if qtype != "a" else "bestaudio/best"
        spd = {"kbs":0,"bytes":0,"last_b":0,"last_t":t0}
        def hook(d):
            if d.get("status")!="downloading": return
            got = d.get("downloaded_bytes",0) or 0
            total = d.get("total_bytes") or d.get("total_bytes_estimate") or 0
            now = time.time(); dt = now - spd["last_t"]
            if dt >= 1:
                spd["kbs"] = max(0, (got - spd["last_b"])/dt/1024)
                spd["last_b"] = got; spd["last_t"] = now
            spd["bytes"] = got
            pct = f"{got/total*100:.0f}%" if total else "…"
            eta = "?"
            if spd["kbs"]>0 and total:
                s = (total-got)/1024/spd["kbs"]
                eta = f"{int(s//60)}د{int(s%60)}ث" if s>=60 else f"{int(s)}ث"
            asyncio.run_coroutine_threadsafe(
                safe_edit(status_msg, f"⬇️ جارٍ التحميل...\n⚡ {fmt_speed(spd['kbs'])}\n📦 {fmt_size(got)}/{fmt_size(total)} [{pct}]  ETA: {eta}"), loop)

        is_yt = is_youtube(url)
        is_pin = is_pinterest(url)
        proxy = get_random_proxy()

        opts = {
            "outtmpl": str(DL_DIR / f"{vid_id}.%(ext)s"),
            "quiet": True, "no_warnings": True, "noprogress": True,
            "socket_timeout": 120, "retries": 15, "fragment_retries": 15,
            "continuedl": not is_pin,
            "concurrent_fragment_downloads": 0 if is_pin else 16,
            "http_chunk_size": 8*1024*1024, "buffersize": 1024*1024,
            "no_mtime": True, "no_playlist": True, "prefer_ffmpeg": True,
            "merge_output_format": "mp4", "format": fmt_str,
            "progress_hooks": [hook], "geo_bypass": True,
            "skip_unavailable_fragments": True, "keep_fragments": False,
            "ignore_no_formats_error": True,
            "no_check_formats": True,
        }
        if proxy:
            opts["proxy"] = proxy
        if is_yt:
            opts["youtube_include_dash_manifest"] = True
            opts["extractor_args"] = {
                "youtube": {"player_client": "android_vr", "formats": "missing_pot"}
            }
            if PO_TOKEN:
                opts["extractor_args"]["youtube"]["po_token"] = f"android_vr.player+{PO_TOKEN}"
        elif not is_pin and shutil.which("aria2c"):
            opts["external_downloader"] = "aria2c"
            opts["external_downloader_args"] = ["-x","8","-s","8","-k","1M"]

        if COOKIE_FILE and os.path.exists(COOKIE_FILE):
            opts["cookiefile"] = COOKIE_FILE

        if is_yt:
            opts["http_headers"] = {"User-Agent": YT_UA, **COMMON_HEADERS}
        elif is_pin:
            opts["http_headers"] = {"User-Agent": PINTEREST_UA, **COMMON_HEADERS}

        if qtype == "a":
            opts.pop("merge_output_format", None)
            opts["postprocessors"] = [{"key":"FFmpegExtractAudio","preferredcodec":"mp3","preferredquality":"128"}]

        filename = None
        try:
            with yt_dlp.YoutubeDL(opts) as ydl:
                info = await loop.run_in_executor(None, lambda: ydl.extract_info(url, download=True))
                raw = ydl.prepare_filename(info)
            filename = _locate_file(raw, info.get("id", vid_id), qtype)
        except Exception as e:
            await status_msg.edit_text(f"❌ {str(e)[:250]}")
            cleanup(vid_id); return

        if not filename or not os.path.exists(filename):
            await status_msg.edit_text("❌ الملف غير موجود."); cleanup(vid_id); return

        size = os.path.getsize(filename)
        if size == 0:
            await status_msg.edit_text("❌ الملف فارغ."); cleanup(vid_id); return

        speed = spd["kbs"]
        title = (info.get("title") or "")[:200]
        uploader = (info.get("uploader") or info.get("channel") or "")[:100]

        if size > MAX_SIZE and qtype != "a":
            await safe_edit(status_msg, "📦 تقسيم...")
            parts = await loop.run_in_executor(None, lambda: split_video(filename, MAX_SIZE))
            if not parts:
                await status_msg.edit_text("❌ فشل التقسيم."); cleanup(vid_id); return
            total = len(parts)
            base_cap = f"<b>{title}</b>\n👤 {uploader}\n📥 {BOT_NAME}\n"
            for i, p in enumerate(parts, 1):
                ps = os.path.getsize(p)
                with open(p,"rb") as vf:
                    await ctx.bot.send_video(chat_id=chat_id, video=vf, caption=f"{base_cap}📦 جزء {i}/{total} | {fmt_size(ps)}", parse_mode="HTML", read_timeout=600, write_timeout=600, supports_streaming=True)
                try: os.remove(p)
                except: pass
            await safe_edit(status_msg, "✅ تم."); db_log(uid, url, title, qtype, size, speed); cleanup(vid_id)
        else:
            elapsed = int(time.time()-t0)
            await safe_edit(status_msg, f"📤 رفع {fmt_size(size)}... ⏱ {elapsed}ث")
            caption = f"<b>{title}</b>\n👤 {uploader}\n⚡ {fmt_speed(speed)} | ⏱ {elapsed}ث\n📥 {BOT_NAME}"
            kw = dict(chat_id=chat_id, caption=caption, parse_mode="HTML", read_timeout=600, write_timeout=600)
            with open(filename,"rb") as f:
                if qtype=="a": await ctx.bot.send_audio(audio=f, title=title[:64], performer=uploader or "YAMD", **kw)
                else: await ctx.bot.send_video(video=f, supports_streaming=True, **kw)
            db_log(uid, url, title, qtype, size, speed)
            try: await status_msg.delete()
            except: pass
            cleanup(vid_id)

async def download_pinterest(ctx, chat_id, url, status_msg, uid):
    loop = asyncio.get_running_loop(); vid_id = f"v{uid}{int(time.time())}"; output = str(DL_DIR / f"{vid_id}.mp4")
    try:
        await safe_edit(status_msg, "🔍 استخراج رابط Pinterest...")
        cmd = ["yt-dlp","-g","--user-agent",PINTEREST_UA,"--no-check-certificate","--no-warnings","--quiet",url]
        if COOKIE_FILE and os.path.exists(COOKIE_FILE): cmd += ["--cookies", COOKIE_FILE]
        proxy = get_random_proxy()
        if proxy: cmd += ["--proxy", proxy]
        proc = await asyncio.create_subprocess_exec(*cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE)
        stdout, stderr = await proc.communicate()
        direct = stdout.decode(errors="ignore").strip().splitlines()[0].strip() if proc.returncode==0 and stdout else ""
        if not direct:
            pin_opts = {"quiet":True,"no_warnings":True,"http_headers":{"User-Agent":PINTEREST_UA}}
            if COOKIE_FILE and os.path.exists(COOKIE_FILE): pin_opts["cookiefile"] = COOKIE_FILE
            if proxy: pin_opts["proxy"] = proxy
            with yt_dlp.YoutubeDL(pin_opts) as ydl:
                info = await loop.run_in_executor(None, lambda: ydl.extract_info(url, download=False))
            for f in info.get("formats",[]):
                u = f.get("url","")
                if u and ("m3u8" in u or "mp4" in u): direct = u; break
        if not direct: raise RuntimeError("لم يتم استخراج رابط مباشر")
        await safe_edit(status_msg, "⬇️ تحميل بـ ffmpeg...")
        ffmpeg_cmd = ["ffmpeg","-y","-loglevel","error","-user_agent",PINTEREST_UA,"-i",direct,"-c","copy","-bsf:a","aac_adtstoasc",output]
        proc2 = await asyncio.create_subprocess_exec(*ffmpeg_cmd)
        await proc2.wait()
        if proc2.returncode!=0: raise RuntimeError("فشل ffmpeg")
        if not os.path.exists(output) or os.path.getsize(output)==0: raise RuntimeError("ملف فارغ")
        size = os.path.getsize(output)
        title = "فيديو Pinterest"; uploader = "Pinterest"
        try:
            with yt_dlp.YoutubeDL({"quiet":True}) as ydl: info = await loop.run_in_executor(None, lambda: ydl.extract_info(url, download=False))
            title = (info.get("title") or title)[:200]; uploader = (info.get("uploader") or info.get("channel") or uploader)[:100]
        except: pass
        if size > MAX_SIZE:
            await safe_edit(status_msg, "📦 تقسيم...")
            parts = await loop.run_in_executor(None, lambda: split_video(output, MAX_SIZE))
            if not parts: await status_msg.edit_text("❌ فشل التقسيم"); cleanup(vid_id); return
            total = len(parts); base = f"<b>{title}</b>\n👤 {uploader}\n📥 {BOT_NAME}\n"
            for i, p in enumerate(parts,1):
                ps = os.path.getsize(p)
                with open(p,"rb") as vf: await ctx.bot.send_video(chat_id=chat_id, video=vf, caption=f"{base}📦 جزء {i}/{total} | {fmt_size(ps)}", parse_mode="HTML", read_timeout=600, write_timeout=600, supports_streaming=True)
                try: os.remove(p)
                except: pass
            await safe_edit(status_msg, "✅ تم.")
        else:
            await safe_edit(status_msg, f"📤 رفع {fmt_size(size)}...")
            kw = dict(chat_id=chat_id, caption=f"<b>{title}</b>\n👤 {uploader}\n📥 {BOT_NAME}", parse_mode="HTML", read_timeout=600, write_timeout=600)
            with open(output,"rb") as f: await ctx.bot.send_video(video=f, supports_streaming=True, **kw)
            try: await status_msg.delete()
            except: pass
        db_log(uid, url, title, "pinterest", size, 0); cleanup(vid_id)
    except Exception as e:
        await status_msg.edit_text(f"❌ فشل تحميل Pinterest: {str(e)[:250]}"); cleanup(vid_id)

# ═══════════════════════════════════════════════════════════
# واجهة المستخدم (إخفاء /admin عن العامة)
# ═══════════════════════════════════════════════════════════
async def cmd_start(update, ctx):
    db_user(update.effective_user)
    msg = f"أهلاً بك في <b>{BOT_NAME}</b>! 🚀\n<b>{BOT_FULL_NAME}</b>\n\n⚡ أرسل رابط الفيديو من أي منصة.\n/about"
    await update.message.reply_text(msg, parse_mode="HTML")

async def cmd_about(update, ctx):
    await update.message.reply_text(
        f"🌟 <b>{BOT_NAME}</b>\n<b>{BOT_FULL_NAME}</b>\n\n"
        "⚡ بوت تحميل سريع واحترافي\n"
        "🎥 تحميل فيديو وصوت بجودات متعددة\n"
        "📦 تقسيم تلقائي للملفات الكبيرة\n"
        "🚀 أداء واستقرار عالي\n\n"
        "👨‍💻 المطور: @Yaaqob_Almahajeri",
        parse_mode="HTML"
    )

async def show_formats(update, ctx, url, status_msg):
    loop = asyncio.get_running_loop()
    try:
        info, v_fmts, best_aud = await loop.run_in_executor(None, extract_formats, url)
    except Exception as e:
        await status_msg.edit_text(f"❌ فشل استخراج التنسيقات: {str(e)[:400]}"); return
    ctx.user_data["url"] = url
    ctx.user_data["formats_cache"] = {v["format_id"]: v for v in v_fmts}
    if best_aud: ctx.user_data["formats_cache"][best_aud["format_id"]] = best_aud
    kb = []
    for v in v_fmts:
        sz = f" (~{fmt_size(v['filesize'])})" if v.get("filesize") else ""
        label = f"🎥 {v['height']}p {v['ext']}{sz}"
        kb.append([InlineKeyboardButton(label, callback_data=f"dl|v|{v['format_id']}")])
    if best_aud:
        sz = f" (~{fmt_size(best_aud['filesize'])})" if best_aud.get("filesize") else ""
        label = f"🔊 صوت MP3 {best_aud['ext']} {int(best_aud['abr'])}kbps{sz}"
        kb.append([InlineKeyboardButton(label, callback_data=f"dl|a|{best_aud['format_id']}")])
    if not kb: await status_msg.edit_text("❌ لا توجد تنسيقات."); return
    await status_msg.edit_text(f"🎞️ <b>{(info.get('title') or 'فيديو')[:200]}</b>\nاختر التنسيق:", reply_markup=InlineKeyboardMarkup(kb), parse_mode="HTML")

async def on_link(update, ctx):
    db_user(update.effective_user)
    url = (update.message.text or "").strip()
    if not url.startswith("http"): await update.message.reply_text("⚠️ أرسل رابطاً صالحاً."); return
    if is_pinterest(url):
        status = await update.message.reply_text("⬇️ جارٍ تحميل Pinterest...")
        asyncio.create_task(download_pinterest(ctx, update.message.chat_id, url, status, update.effective_user.id))
        return
    status_msg = await update.message.reply_text("🔍 فحص التنسيقات...")
    await show_formats(update, ctx, url, status_msg)

async def on_format_choice(update, ctx):
    q = update.callback_query; await q.answer()
    parts = (q.data or "").split("|")
    if len(parts) < 3: return
    qtype, fid = parts[1], parts[2]
    url = ctx.user_data.get("url")
    cache = ctx.user_data.get("formats_cache", {})
    selected = cache.get(fid)
    if not selected or not url: await q.edit_message_text("❌ الجلسة منتهية."); return
    has_audio = selected.get("acodec") not in [None, "none", "None"]
    has_video = selected.get("vcodec") not in [None, "none", "None"]
    if qtype == "a": fmt_str = "bestaudio[ext=m4a]/bestaudio[ext=webm]/bestaudio/best"
    elif has_video and has_audio: fmt_str = fid
    elif has_video: fmt_str = f"{fid}+bestaudio[ext=m4a]/{fid}+bestaudio/bestvideo+bestaudio/best"
    else: fmt_str = "bestvideo+bestaudio/best"
    desc = "صوت" if qtype == "a" else "فيديو"
    await q.edit_message_text(f"⬇️ جارٍ تحميل {desc}...")
    asyncio.create_task(do_download(ctx, q.message.chat_id, url, fmt_str, qtype, q.message, q.from_user.id))

# ═══════════════════════════════════════════════════════════
# لوحة الإدارة (تفاصيل متقدمة + IP)
# ═══════════════════════════════════════════════════════════
async def cmd_admin(update, ctx):
    if update.effective_user.id != ADMIN_ID: await update.message.reply_text("⛔ للمشرف فقط."); return
    ytdlp_ver = "❌"
    try: ytdlp_ver = yt_dlp.version.__version__
    except: pass
    kb = [[InlineKeyboardButton("👥 المستخدمون", callback_data="a|users")],
          [InlineKeyboardButton("📜 آخر التحميلات", callback_data="a|dls")],
          [InlineKeyboardButton("📊 إحصائيات", callback_data="a|stats")],
          [InlineKeyboardButton("🗑 تنظيف مؤقت", callback_data="a|clean")]]
    await update.message.reply_text(
        f"🛡️ <b>YAMD Admin</b>\nyt-dlp: <code>{ytdlp_ver}</code>\n"
        f"aria2: {'✅' if shutil.which('aria2c') else '❌'} | ffmpeg: {'✅' if shutil.which('ffmpeg') else '❌'}\n"
        f"🍪 Cookies: {'✅' if COOKIE_FILE else '❌'}\n"
        f"🌐 Proxies: {len(PROXY_POOL)}\n"
        f"🔑 PO Token: {'✅' if PO_TOKEN else '❌'}",
        reply_markup=InlineKeyboardMarkup(kb), parse_mode="HTML")

async def on_admin(update, ctx):
    q = update.callback_query
    if q.from_user.id != ADMIN_ID: await q.answer("⛔", show_alert=True); return
    await q.answer(); act = q.data.split("|")[1]
    if act == "users":
        rows = db.execute("""
            SELECT u.uid, u.username, u.fname, u.lname, u.lang, u.premium,
                   u.cnt, u.active, u.seen, u.ip
            FROM users u
            ORDER BY u.active DESC
            LIMIT 15
        """).fetchall()
        t = "👥 <b>آخر 15 مستخدم (تحليل متقدم مع IP)</b>

"
        for uid, un, fn, ln, lang, premium, cnt, active, seen, ip in rows:
            total_size = db.execute("SELECT COALESCE(SUM(size),0) FROM downloads WHERE uid=?", (uid,)).fetchone()[0]
            total_dl = db.execute("SELECT COUNT(*) FROM downloads WHERE uid=?", (uid,)).fetchone()[0]
            audio_cnt = db.execute("SELECT COUNT(*) FROM downloads WHERE uid=? AND quality='a'", (uid,)).fetchone()[0]
            avg_speed = db.execute("SELECT COALESCE(AVG(speed),0) FROM downloads WHERE uid=?", (uid,)).fetchone()[0]
            last_three = db.execute("SELECT title, ts FROM downloads WHERE uid=? ORDER BY id DESC LIMIT 3", (uid,)).fetchall()
            
            full_name = fn
            if ln: full_name += " " + ln
            name = un or full_name or "Unknown"
            first_seen = (seen or "")[:10] if seen else "?"
            last_active = (active or "")[:10] if active else "?"
            days_active = "?"
            if seen and active:
                try:
                    days_active = str((datetime.strptime(active[:10], "%Y-%m-%d") - datetime.strptime(seen[:10], "%Y-%m-%d")).days) + " يوم"
                except: pass
            lang_str = lang if lang else "غير محدد"
            premium_icon = "🌟" if premium else ""
            user_ip = ip if ip else "غير معروف"
            t += (f"• {premium_icon} <code>{uid}</code> {name}
"
                  f"  @{un if un else 'لا يوجد'} | 🌐 {lang_str}
"
                  f"  🌍 IP: {user_ip}
"
                  f"  🔗 tg://user?id={uid}
"
                  f"  🗓 أول: {first_seen} | آخر: {last_active} | مدة: {days_active}
"
                  f"  📥 التحميلات: {total_dl} (🎥 فيديو: {total_dl - audio_cnt} | 🔊 صوت: {audio_cnt})
"
                  f"  📦 حجم: {fmt_size(total_size)} | ⚡ متوسط السرعة: {fmt_speed(avg_speed)}
")
            if last_three:
                t += "  🎬 آخر التحميلات:
"
                for i, (title, date) in enumerate(last_three, 1):
                    t += f"    {i}. {title[:60]}
"
                    if date: t += f"       🕒 {date[:16]}
"
            t += "
"
        await q.edit_message_text(t or "لا يوجد.", parse_mode="HTML")    elif act == "dls":
        rows = db.execute("SELECT d.uid,d.title,d.quality,d.size,d.speed,d.ts,u.username FROM downloads d LEFT JOIN users u ON d.uid=u.uid ORDER BY d.id DESC LIMIT 20").fetchall()
        t = "📜 <b>آخر 20 تحميلة</b>\n\n"
        for uid,ttl,qual,sz,spd,ts,un in rows: t += f"• <b>{un or uid}</b> | {qual} | {fmt_size(sz) if sz else '?'} | {fmt_speed(spd) if spd else '?'}\n  {(ttl or '')[:35]}\n"
        await q.edit_message_text(t or "لا توجد.", parse_mode="HTML")
    elif act == "stats":
        uc = db.execute("SELECT COUNT(*) FROM users").fetchone()[0]; dc = db.execute("SELECT COUNT(*) FROM downloads").fetchone()[0]; avg = db.execute("SELECT AVG(speed) FROM downloads").fetchone()[0] or 0
        await q.edit_message_text(f"📊 <b>YAMD Stats</b>\n\n👥 {uc} مستخدم\n📥 {dc} تحميلة\n⚡ متوسط: {fmt_speed(avg)}\naria2: {'✅' if shutil.which('aria2c') else '❌'}\n🍪 Cookies: {'✅' if COOKIE_FILE else '❌'}\n🌐 Proxies: {len(PROXY_POOL)}\n🔑 PO Token: {'✅' if PO_TOKEN else '❌'}", parse_mode="HTML")
    elif act == "clean":
        for f in DL_DIR.iterdir():
            try:
                if f.is_file(): f.unlink()
            except: pass
        await q.edit_message_text("🗑 تم تنظيف المجلد المؤقت.")

async def on_error(update, ctx): logger.error(f"[ERROR] {ctx.error}", exc_info=ctx.error)

# ═══════════════════════════════════════════════════════════
# خادم الويب (Webhook) مع التقاط IP
# ═══════════════════════════════════════════════════════════
async def main():
    if not BOT_TOKEN or not WEBHOOK_URL: raise RuntimeError("Missing BOT_TOKEN or WEBHOOK_URL")
    await _ensure_ytdlp_updated()
    tmp = Application.builder().token(BOT_TOKEN).build()
    await tmp.bot.delete_webhook(drop_pending_updates=True)
    logger.info("🧹 Old webhook removed")
    app = Application.builder().token(BOT_TOKEN).connect_timeout(30).read_timeout(600).write_timeout(600).pool_timeout(120).concurrent_updates(2).build()
    app.add_handler(CommandHandler("start", cmd_start))
    app.add_handler(CommandHandler("about", cmd_about))
    app.add_handler(CommandHandler("admin", cmd_admin))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, on_link))
    app.add_handler(CallbackQueryHandler(on_admin, pattern=r"^a\|"))
    app.add_handler(CallbackQueryHandler(on_format_choice, pattern=r"^dl\|"))
    app.add_error_handler(on_error)
    await app.initialize(); await app.start()
    webhook_url = f"{WEBHOOK_URL}/{BOT_TOKEN}"
    await app.bot.set_webhook(url=webhook_url, allowed_updates=["message","callback_query"])
    logger.info("✅ Webhook configured")
    asyncio.create_task(cleanup_task())
    web_app = web.Application()
    async def webhook_handler(request):
        try:
            data = await request.json()
            update = Update.de_json(data, app.bot)
            if update and update.effective_user:
                user_ip = request.remote
                if user_ip:
                    db.execute("UPDATE users SET ip=? WHERE uid=?", (user_ip, update.effective_user.id))
                    db.commit()
            await app.process_update(update)
            return web.Response(text="ok")
        except Exception as e:
            logger.error(f"Webhook error: {e}")
            return web.Response(status=500, text="error")
    web_app.router.add_post(f"/{BOT_TOKEN}", webhook_handler)
    web_app.router.add_get("/", lambda r: web.Response(text="YAMD is running!"))
    runner = web.AppRunner(web_app); await runner.setup()
    site = web.TCPSite(runner, "0.0.0.0", PORT); await site.start()
    logger.info(f"🌐 Webhook server on port {PORT}")
    try:
        while True: await asyncio.sleep(3600)
    except (KeyboardInterrupt, SystemExit):
        logger.info("Shutting down...")
        await app.bot.delete_webhook(drop_pending_updates=True); await app.stop(); await app.shutdown()
        logger.info("Bot stopped cleanly")

if __name__ == "__main__":
    try: asyncio.run(main())
    except Exception: logger.critical(f"Fatal: {traceback.format_exc()}"); sys.exit(1)
