import os, sys, time, asyncio, logging, sqlite3, shutil, subprocess, math, traceback, json
from pathlib import Path
from datetime import datetime
from collections import defaultdict

from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, MessageHandler, filters, CallbackQueryHandler, ContextTypes
import yt_dlp
from aiohttp import web

BOT_NAME      = "⚡ YAMD – Ultra Speed"
BOT_FULL_NAME = "YAAQOB ALMAHAJERI MEDIA DOWNLOADER"

BOT_TOKEN   = os.environ.get("BOT_TOKEN", "")
ADMIN_ID    = int(os.environ.get("ADMIN_ID", "0"))
WEBHOOK_URL = os.environ.get("WEBHOOK_URL", "")

MAX_SIZE = 48 * 1024 * 1024
DL_DIR   = Path.home() / "yamd_dl"
DL_DIR.mkdir(exist_ok=True)

HAS_FFMPEG = bool(shutil.which("ffmpeg"))
HAS_ARIA2  = bool(shutil.which("aria2c"))

DOWNLOAD_SEM = asyncio.Semaphore(2)

# ─── الكوكيز: الأولوية لـ COOKIES_TEXT ثم Secret File ────
COOKIE_FILE = None
COOKIE_TMP  = "/tmp/yamd_cookies.txt"

# 1. COOKIES_TEXT (الأسهل)
COOKIES_TEXT = os.environ.get("COOKIES_TEXT", "")
if COOKIES_TEXT:
    with open(COOKIE_TMP, "w", encoding="utf-8") as f:
        f.write("# Netscape HTTP Cookie File\n# generated by YAMD\n")
        f.write(COOKIES_TEXT)
    COOKIE_FILE = COOKIE_TMP
    logger = logging.getLogger("YAMD")
    logger.info("🍪 Cookies loaded from COOKIES_TEXT")
else:
    # 2. Secret File
    SECRET_FILE = "/etc/secrets/cookies.txt"
    if os.path.exists(SECRET_FILE):
        try:
            shutil.copy2(SECRET_FILE, COOKIE_TMP)
            COOKIE_FILE = COOKIE_TMP
            logger = logging.getLogger("YAMD")
            logger.info("🍪 Cookies copied from Render Secret File")
        except Exception as e:
            logging.error(f"Failed to copy secret file: {e}")
    else:
        logging.warning("⚠️ No cookies found (COOKIES_TEXT or Secret File). YouTube may require sign-in.")

# ─── Logging ────────────────────────────
logging.basicConfig(level=logging.WARNING,
    format="%(asctime)s [%(levelname)s] %(message)s", datefmt="%H:%M:%S",
    handlers=[logging.StreamHandler(sys.stdout), logging.FileHandler("yamd.log")])
logger = logging.getLogger("YAMD")
logger.setLevel(logging.INFO)
for lib in ("httpx","httpcore","telegram","hpack","asyncio"):
    logging.getLogger(lib).setLevel(logging.ERROR)

# ─── DB ─────────────────────────────────
db = sqlite3.connect("yamd.db", check_same_thread=False)
db.execute("PRAGMA journal_mode=WAL")
db.execute("PRAGMA synchronous=NORMAL")
def _setup_db():
    db.execute("CREATE TABLE IF NOT EXISTS users(uid INTEGER PRIMARY KEY, username TEXT, fname TEXT, seen TEXT, active TEXT, cnt INTEGER DEFAULT 0)")
    db.execute("CREATE TABLE IF NOT EXISTS downloads(id INTEGER PRIMARY KEY AUTOINCREMENT, uid INTEGER, url TEXT, title TEXT, quality TEXT, size INTEGER, speed REAL, ts TEXT)")
    db.commit()
_setup_db()

def db_user(u):
    now = datetime.now().isoformat()
    db.execute("INSERT INTO users(uid,username,fname,seen,active) VALUES(?,?,?,?,?) ON CONFLICT(uid) DO UPDATE SET active=excluded.active, username=COALESCE(excluded.username,username), fname=COALESCE(excluded.fname,fname)", (u.id, u.username or "", u.first_name or "", now, now))
    db.commit()

def db_log(uid, url, title, qkey, size, speed):
    db.execute("INSERT INTO downloads(uid,url,title,quality,size,speed,ts) VALUES(?,?,?,?,?,?,?)", (uid, url, title, qkey, size, round(speed,1), datetime.now().isoformat()))
    db.execute("UPDATE users SET cnt=cnt+1 WHERE uid=?", (uid,))
    db.commit()

def fmt_size(b):
    if b >= 1024**3: return f"{b/1024**3:.1f}GB"
    return f"{b/1024**2:.1f}MB"

def fmt_speed(kbs):
    if kbs >= 1024: return f"{kbs/1024:.1f}MB/s"
    return f"{kbs:.0f}KB/s"

_edit_ts = defaultdict(float)
async def safe_edit(msg, text, markup=None):
    if time.time() - _edit_ts[msg.message_id] < 3: return
    try:
        await msg.edit_text(text, reply_markup=markup)
        _edit_ts[msg.message_id] = time.time()
    except: pass

def find_file(vid_id):
    cands = sorted([f for f in DL_DIR.glob(f"{vid_id}*") if f.is_file()], key=lambda f: f.stat().st_size, reverse=True)
    return str(cands[0]) if cands else None

def cleanup(vid_id):
    for f in DL_DIR.glob(f"{vid_id}*"):
        try: f.unlink()
        except: pass

def split_video(filepath, max_part_size=MAX_SIZE):
    if not HAS_FFMPEG: return None
    base = os.path.splitext(filepath)[0]
    pattern = f"{base}_part%03d.mp4"
    try:
        dur = float(subprocess.run(["ffprobe","-v","quiet","-show_entries","format=duration","-of","csv=p=0",filepath], capture_output=True,text=True).stdout.strip())
    except: return None
    if not dur: return None
    total_size = os.path.getsize(filepath)
    parts_count = math.ceil(total_size / max_part_size)
    seg = math.ceil(dur / parts_count) + 1
    subprocess.run(["ffmpeg","-i",filepath,"-c","copy","-map","0","-f","segment","-segment_time",str(seg),"-reset_timestamps","1","-segment_format","mp4",pattern], check=True, capture_output=True)
    return [str(p) for p in sorted(Path(base).parent.glob(f"{Path(filepath).stem}_part*.mp4"))]

async def cleanup_task():
    while True:
        now = time.time()
        for f in DL_DIR.glob("*"):
            try:
                if now - f.stat().st_mtime > 3600:
                    f.unlink()
            except: pass
        await asyncio.sleep(1800)

# ─── Commands ───────────────────────────
async def cmd_start(update, ctx):
    db_user(update.effective_user)
    msg = (f"أهلاً بك في <b>{BOT_NAME}</b>! 🚀\n"
           f"<b>{BOT_FULL_NAME}</b>\n\n"
           "⚡ أرسل رابط الفيديو من أي منصة وسأحمّله بأقصى سرعة.\n"
           "/about | /admin")
    if update.effective_user.id == ADMIN_ID: msg += "\n🛡️ لوحة التحكم: /admin"
    await update.message.reply_text(msg, parse_mode="HTML")

async def cmd_about(update, ctx):
    await update.message.reply_text(
        f"🌟 <b>{BOT_NAME}</b>\n<b>{BOT_FULL_NAME}</b>\n\n"
        "⚡ أسرع بوت تحميل على تلغرام.\n"
        "✅ تجاوز حظر يوتيوب بذكاء\n"
        "📦 تقسيم ذكي للملفات الكبيرة\n"
        "🚀 aria2c + nightly yt-dlp\n"
        "السرعة هي هويتنا.", parse_mode="HTML")

async def on_link(update, ctx):
    db_user(update.effective_user)
    url = update.message.text.strip()
    if not url.startswith("http"):
        await update.message.reply_text("⚠️ أرسل رابطاً صالحاً.")
        return
    status = await update.message.reply_text("⬇️ جارٍ التحميل...")
    asyncio.create_task(do_download(ctx, update.message.chat_id, url, "auto", status, update.effective_user.id))

async def do_download(ctx, chat_id, url, qkey, status_msg, uid):
    async with DOWNLOAD_SEM:
        loop = asyncio.get_running_loop()
        t0 = time.time()
        vid_id = f"v{uid}{int(t0)}"
        spd = {"kbs":0,"bytes":0,"last_b":0,"last_t":t0}
        def hook(d):
            if d.get("status")!="downloading": return
            got = d.get("downloaded_bytes") or 0
            total = d.get("total_bytes") or d.get("total_bytes_estimate") or 0
            now = time.time()
            dt = now - spd["last_t"]
            if dt >= 1:
                spd["kbs"] = max(0, (got - spd["last_b"]) / dt / 1024)
                spd["last_b"] = got; spd["last_t"] = now
            spd["bytes"] = got
            kbs = spd["kbs"]
            pct = f"{got/total*100:.0f}%" if total else "…"
            eta = "?"
            if kbs>0 and total:
                s = (total - got) / 1024 / kbs
                eta = f"{int(s//60)}د{int(s%60)}ث" if s>=60 else f"{int(s)}ث"
            asyncio.run_coroutine_threadsafe(
                safe_edit(status_msg, f"⬇️ جارٍ التحميل...\n⚡ {fmt_speed(kbs)}\n📦 {fmt_size(got)}/{fmt_size(total)} [{pct}]  ETA: {eta}"),
                loop)

        is_youtube = "youtube.com" in url or "youtu.be" in url
        is_pin = "pin.it" in url or "pinterest" in url.lower()

        format_list = [
            "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]",
            "bv*[height<=720][ext=mp4]+ba[ext=m4a]/b[height<=720]",
            "bv*[height<=480][ext=mp4]+ba[ext=m4a]/b[height<=480]",
            "best"
        ]
        youtube_clients = [["android"], ["tv_embedded"], ["ios"]]

        filename = None
        for fmt in format_list:
            if filename: break
            for client_list in (youtube_clients if is_youtube else [[]]):
                opts = {
                    "outtmpl": str(DL_DIR / f"{vid_id}.%(ext)s"),
                    "quiet": True, "no_warnings": True, "noprogress": True,
                    "socket_timeout": 120,
                    "retries": 15, "fragment_retries": 15,
                    "no_check_certificate": True,
                    "continuedl": True,
                    "concurrent_fragment_downloads": 4,
                    "http_chunk_size": 4 * 1024 * 1024,
                    "buffersize": 1024 * 1024,
                    "no_mtime": True, "no_playlist": True,
                    "prefer_ffmpeg": True,
                    "merge_output_format": "mp4",
                    "format": fmt,
                    "progress_hooks": [hook],
                    "throttledratelimit": 1000000,
                    "geo_bypass": True,
                }
                if HAS_ARIA2:
                    opts["external_downloader"] = "aria2c"
                    opts["external_downloader_args"] = ["-x", "8", "-s", "8", "-k", "1M"]
                if COOKIE_FILE and os.path.exists(COOKIE_FILE):
                    opts["cookiefile"] = COOKIE_FILE
                if is_youtube:
                    opts["http_headers"] = {
                        "User-Agent": "com.google.android.youtube/20.10.38 (Linux; Android 14)",
                        "Accept-Language": "en-US,en;q=0.9",
                    }
                    if client_list:
                        opts["extractor_args"] = {"youtube": {"player_client": client_list}}
                if qkey == "audio":
                    del opts["merge_output_format"]
                    opts["postprocessors"] = [{"key": "FFmpegExtractAudio", "preferredcodec": "mp3", "preferredquality": "128"}]

                try:
                    with yt_dlp.YoutubeDL(opts) as ydl:
                        info = await loop.run_in_executor(None, lambda: ydl.extract_info(url, download=True))
                        raw = ydl.prepare_filename(info)
                    filename = _locate_file(raw, info.get("id", vid_id), qkey)
                    if filename: break
                except Exception as e:
                    err = str(e)
                    if "format" in err.lower() and "not available" in err.lower():
                        continue
                    elif "Sign in" in err or "bot" in err:
                        continue
                    else:
                        await status_msg.edit_text(f"❌ {err[:200]}")
                        cleanup(vid_id)
                        return

        if not filename:
            await status_msg.edit_text("❌ فشلت كل محاولات التحميل. جرب جودة أقل.")
            cleanup(vid_id)
            return

        size = os.path.getsize(filename)
        speed = spd["kbs"]
        title = (info.get("title") or "")[:200]

        if size > MAX_SIZE and qkey != "audio":
            await safe_edit(status_msg, "📦 تقسيم...")
            parts = await loop.run_in_executor(None, lambda: split_video(filename, MAX_SIZE))
            if not parts:
                await status_msg.edit_text("❌ فشل التقسيم.")
                cleanup(vid_id)
                return
            total = len(parts)
            base_cap = f"<b>{title}</b>\n👤 {info.get('uploader','')}\n📥 {BOT_NAME}\n"
            for i, p in enumerate(parts, 1):
                ps = os.path.getsize(p)
                with open(p, "rb") as vf:
                    await ctx.bot.send_video(chat_id=chat_id, video=vf,
                                             caption=f"{base_cap}📦 جزء {i}/{total} | {fmt_size(ps)}",
                                             parse_mode="HTML", read_timeout=600, write_timeout=600,
                                             supports_streaming=True)
                os.remove(p)
            await safe_edit(status_msg, "✅ تم.")
            db_log(uid, url, title, qkey, size, speed)
            await asyncio.sleep(2)
            await status_msg.delete()
        else:
            elapsed = int(time.time() - t0)
            await safe_edit(status_msg, f"📤 رفع {fmt_size(size)}... ⏱ {elapsed}ث")
            caption = f"<b>{title}</b>\n👤 {info.get('uploader','')}\n⚡ {fmt_speed(speed)} | ⏱ {elapsed}ث\n📥 {BOT_NAME}"
            kw = dict(chat_id=chat_id, caption=caption, parse_mode="HTML", read_timeout=600, write_timeout=600)
            with open(filename, 'rb') as f:
                if qkey == "audio":
                    await ctx.bot.send_audio(audio=f, title=title[:64], performer=info.get('uploader','YAMD'), **kw)
                else:
                    await ctx.bot.send_video(video=f, supports_streaming=True, **kw)
            db_log(uid, url, title, qkey, size, speed)
            await status_msg.delete()

def _locate_file(raw, vid_id, qkey):
    ext_list = (["mp3"] if qkey=="audio" else ["mp4","mkv","webm",""])
    for ext in ext_list:
        candidate = os.path.splitext(raw)[0] + (f".{ext}" if ext else "")
        if os.path.exists(candidate):
            return candidate
    cands = sorted([f for f in DL_DIR.glob(f"{vid_id}*") if f.is_file()],
                   key=lambda f: f.stat().st_size, reverse=True)
    return str(cands[0]) if cands else None

# ─── Admin ───────────────────────────────
async def cmd_admin(update, ctx):
    if update.effective_user.id != ADMIN_ID: await update.message.reply_text("⛔ للمشرف فقط."); return
    kb = [[InlineKeyboardButton("👥 المستخدمون", callback_data="a|users")],
          [InlineKeyboardButton("📜 آخر التحميلات", callback_data="a|dls")],
          [InlineKeyboardButton("📊 إحصائيات", callback_data="a|stats")],
          [InlineKeyboardButton("🗑 تنظيف مؤقت", callback_data="a|clean")]]
    await update.message.reply_text(f"🛡️ <b>YAMD Admin</b>\naria2: {'✅' if HAS_ARIA2 else '❌'} | ffmpeg: {'✅' if HAS_FFMPEG else '❌'}\n🍪 Cookies: {'✅' if COOKIE_FILE else '❌'}", reply_markup=InlineKeyboardMarkup(kb), parse_mode="HTML")

async def on_admin(update, ctx):
    q = update.callback_query
    if q.from_user.id != ADMIN_ID: await q.answer("⛔", show_alert=True); return
    await q.answer()
    act = q.data.split("|")[1]
    if act == "users":
        rows = db.execute("SELECT uid,username,fname,cnt,active FROM users ORDER BY active DESC LIMIT 15").fetchall()
        t = "👥 <b>آخر 15 مستخدم</b>\n\n"
        for uid,un,fn,cnt,ac in rows: t += f"• <code>{uid}</code> {un or fn}  ⬇️{cnt}  {(ac or '')[:10]}\n"
        await q.edit_message_text(t or "لا يوجد.", parse_mode="HTML")
    elif act == "dls":
        rows = db.execute("SELECT d.uid,d.title,d.quality,d.size,d.speed,d.ts,u.username FROM downloads d LEFT JOIN users u ON d.uid=u.uid ORDER BY d.id DESC LIMIT 20").fetchall()
        t = "📜 <b>آخر 20 تحميلة</b>\n\n"
        for uid,ttl,qual,sz,spd,ts,un in rows: t += f"• <b>{un or uid}</b> | {qual} | {fmt_size(sz) if sz else '?'} | {fmt_speed(spd) if spd else '?'}\n  {(ttl or '')[:35]}\n"
        await q.edit_message_text(t or "لا توجد.", parse_mode="HTML")
    elif act == "stats":
        uc = db.execute("SELECT COUNT(*) FROM users").fetchone()[0]
        dc = db.execute("SELECT COUNT(*) FROM downloads").fetchone()[0]
        avg = db.execute("SELECT AVG(speed) FROM downloads").fetchone()[0] or 0
        await q.edit_message_text(f"📊 <b>YAMD Stats</b>\n\n👥 {uc} مستخدم\n📥 {dc} تحميلة\n⚡ متوسط: {fmt_speed(avg)}\naria2: {'✅' if HAS_ARIA2 else '❌'}\n🍪 Cookies: {'✅' if COOKIE_FILE else '❌'}", parse_mode="HTML")
    elif act == "clean":
        for f in DL_DIR.iterdir(): f.unlink()
        await q.edit_message_text("🗑 تم تنظيف المجلد المؤقت.")

async def on_quality(update, ctx):
    q = update.callback_query
    await q.answer()
    parts = q.data.split("|", 2)
    qkey = parts[1]
    url = parts[2] if len(parts) > 2 else ctx.user_data.get("url","")
    if not url: await q.edit_message_text("❌ انتهت الجلسة."); return
    await q.edit_message_text("⬇️ جارٍ التحميل...")
    asyncio.create_task(do_download(ctx, q.message.chat_id, url, qkey, q.message, q.from_user.id))

async def on_error(update, ctx):
    logger.error(f"[ERROR] {ctx.error}", exc_info=ctx.error)

# ─── Webhook Server ──────────────────────
async def main():
    app_bot = Application.builder().token(BOT_TOKEN).build()
    await app_bot.bot.delete_webhook(drop_pending_updates=True)
    logger.info("🧹 Old webhook removed")

    app = (Application.builder().token(BOT_TOKEN)
           .connect_timeout(30).read_timeout(600).write_timeout(600)
           .pool_timeout(120).concurrent_updates(2).build())

    app.add_handler(CommandHandler("start", cmd_start))
    app.add_handler(CommandHandler("about", cmd_about))
    app.add_handler(CommandHandler("admin", cmd_admin))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, on_link))
    app.add_handler(CallbackQueryHandler(on_admin, pattern=r"^a\|"))
    app.add_handler(CallbackQueryHandler(on_quality, pattern=r"^q\|"))
    app.add_error_handler(on_error)

    await app.initialize()
    await app.start()

    webhook_url = f"{WEBHOOK_URL}/{BOT_TOKEN}"
    await app.bot.set_webhook(url=webhook_url, allowed_updates=["message", "callback_query"])
    logger.info("✅ Webhook configured")

    asyncio.create_task(cleanup_task())

    web_app = web.Application()
    async def telegram_webhook(request):
        data = await request.json()
        update = Update.de_json(data, app.bot)
        await app.process_update(update)
        return web.Response()
    web_app.router.add_post(f"/{BOT_TOKEN}", telegram_webhook)
    web_app.router.add_get("/", lambda r: web.Response(text="YAMD is running!"))

    runner = web.AppRunner(web_app)
    await runner.setup()
    port = int(os.environ.get("PORT", 8080))
    site = web.TCPSite(runner, "0.0.0.0", port)
    await site.start()
    logger.info(f"🌐 Webhook server listening on port {port}")

    try:
        while True:
            await asyncio.sleep(3600)
    except (KeyboardInterrupt, SystemExit):
        logger.info("Shutting down...")
        await app.bot.delete_webhook(drop_pending_updates=True)
        await app.stop()
        await app.shutdown()
        logger.info("Bot stopped cleanly")

if __name__ == "__main__":
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        loop.run_until_complete(main())
    except Exception:
        logger.critical(f"Fatal: {traceback.format_exc()}")
        sys.exit(1)
    finally:
        loop.close()
